### ISSUE TITLE
Please release uncompiled code

### ISSUE THREAD

**Issue by A-nglea** [WKS410/WKS-KEY-Services#1]
a pyc is of no use if links to windows executables are are contained within the pyc.  
Please release raw code!

**Comment by WKS410** [comment]
it does not actually have links to windows executables

**Comment by A-nglea** [comment]
No but that isn't the point. Your release of the Pluto TV downloader did. And it was unuseable on Linux. Why hide code?

**Comment by WKS410** [comment]
does not work on Linux because it is not made for Linux.
I guess the error was due to the binaries
it is only made for windows

**Comment by A-nglea** [comment]
But that is my point. Python is universal. Provide python code and anyone can run it. ffmpeg, N_M3u8DL-RE, yt-dlp, mkvmerge, mp4decrypt, shaka-packager all run on Linux they just don't have 'exe' as a file ending and do not need path locations as we put stuff like that in our $PATH variable. 
Why so resistant to helping Linux users?

**Comment by WKS410** [comment]
I'm not a Linux user but I can do maybe some modification when I have time, and this is not the right place to make an Issues of another script.
I only work with windows files, that's why the plutotv script only works on windows.
you can send messages in discord, apparently you are registered in the group
